---
language: go
go:
  - "1.13.4"

services: docker

os:
  - windows
  - linux
  - osx

before_install:
  # Install dependencies
  - GO111MODULE=on go mod download
  # Style checks
  - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true
  - GO111MODULE=on go vet $(go list ./...) || true

script:
  # We need to stash the architecture value for GOOS/GOARCH.
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export PYGMY_PATH=pygmy-go-linux-x86; fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then export PYGMY_PATH=pygmy-go-darwin; fi
  - if [ $TRAVIS_OS_NAME == "windows" ]; then export PYGMY_PATH=pygmy-go.exe; fi

  # Build Pygmy without make
  - docker build -t pygmy-go .
  - docker run -v ${PWD}:/data pygmy-go cp ${PYGMY_PATH} /data/builds/${PYGMY_PATH}

  # Launch Pygmy
  - builds/${PYGMY_PATH} --config .travis.pygmy.yml up
  - builds/${PYGMY_PATH} --config .travis.pygmy.yml status

  # Test Pygmy
  - curl --HEAD http://docker.amazee.io:8080/stats
  #- curl http://mailhog.docker.amazee.io:1025

  # Remove and clean Pygmy
  - builds/${PYGMY_PATH} --config .travis.pygmy.yml down
  - builds/${PYGMY_PATH} --config .travis.pygmy.yml clean
  - docker image rm pygmy-go

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY