---
language: go
go:
  - "1.13.4"

services: docker

before_install:
  # Install dependencies
  - GO111MODULE=on go mod download
  # Style checks
  - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true
  - GO111MODULE=on go vet $(go list ./...) || true

script:
  - make
  - builds/pygmy-go-linux-x86 --config .travis.pygmy.yml up
  - builds/pygmy-go-linux-x86 --config .travis.pygmy.yml status
  - builds/pygmy-go-linux-x86 --config .travis.pygmy.yml down
  - builds/pygmy-go-linux-x86 --config .travis.pygmy.yml clean

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY