---
language: go
go:
  - "1.13.4"

services: docker

before_install:
  # Install dependencies
  - GO111MODULE=on go mod download
#  - GO111MODULE=on go install .
  # Style checks
  - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true
  - GO111MODULE=on go vet $(go list ./...) || true

script:
  - make
  - builds/pygmy-go-linux-x86 up
  - builds/pygmy-go-linux-x86 down
  - builds/pygmy-go-linux-x86 clean

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY