services:

  amazeeio-ssh-agent:
    Config:
      Labels:
        - "pygmy.disabled": "false"

  amazeeio-ssh-agent-show-keys:
    Config:
      Labels:
        - "pygmy.disabled": "true"

  amazeeio-ssh-agent-add-key:
    Config:
      Labels:
        - "pygmy.disabled": "true"

  amazeeio-portainer:
    Config:
      Image: portainer/portainer
      Env:
        - "AMAZEEIO=AMAZEEIO"
        - "AMAZEEIO_URL=portainer.docker.amazee.io"
        - "AMAZEEIO_HTTP_PORT=9000"
      Labels:
        - "pygmy": "pygmy"
        - "pygmy.name": "amazeeio-portainer"
        - "pygmy.weight": "23"
        - "pygmy.url": "http://portainer.docker.amazee.io"
      ExposedPorts:
        9000/tcp: {}
    HostConfig:
      Binds:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      PortBindings:
        8000/tcp:
          -
            HostPort: 8200
        9000/tcp:
          -
            HostPort: 8100

volumes:
  portainer_data:
    Name: portainer_data