---
language: go
go:
  - "1.13.4"

matrix:
  include:

    - os: linux
      services: docker
      before_install:
        - go mod download
        - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true;
        - GO111MODULE=on go vet $(go list ./...) || true;

        - docker build -t pygmy-go .;
      script:
        - export PYGMY_PATH=pygmy-go-linux-x86;
        - docker run -v ${PWD}:/data pygmy-go cp ${PYGMY_PATH} /data/builds/${PYGMY_PATH};
        - builds/${PYGMY_PATH} --config .travis.pygmy.yml up;
        - builds/${PYGMY_PATH} --config .travis.pygmy.yml status;
        - curl --HEAD http://docker.amazee.io/stats
        - builds/${PYGMY_PATH} --config .travis.pygmy.yml down;
        - builds/${PYGMY_PATH} --config .travis.pygmy.yml clean;
        - docker image rm pygmy-go --force || true;

    - os: windows
      services: docker
      before_install:
        - go mod download
        - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true;
        - GO111MODULE=on go vet $(go list ./...) || true;

      script:
        - export PYGMY_PATH=pygmy-go.exe;

        - go mod vendor
        - rm -f go.mod
        - rm -f go.sum
        - go build -o pygmy-go.exe .
        - cp pygmy-go.exe builds/pygmy-go.exe

        - builds/${PYGMY_PATH} --config .travis.pygmy.yml status;

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY