---
language: go
go:
  - "1.13.4"

services: docker

os:
  - windows
  - linux
  - osx

before_install:
  # Install dependencies
  - GO111MODULE=on go mod download
  # Style checks
  - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go")) || true
  - GO111MODULE=on go vet $(go list ./...) || true

script:
  # Build Pygmy
  - make

  # Launch Pygmy
  - builds/pygmy-go.exe --config .travis.pygmy.yml up
  - builds/pygmy-go.exe --config .travis.pygmy.yml status

  # Test Pygmy
  - curl --HEAD http://docker.amazee.io:8080/stats
  #- curl http://mailhog.docker.amazee.io:1025

  # Remove and clean Pygmy
  - builds/pygmy-go.exe --config .travis.pygmy.yml down
  - builds/pygmy-go.exe --config .travis.pygmy.yml clean

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY