apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mailhog
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 1025
    protocol: ""
    targetPort: 0
  selector:
    service: mailhog
status:
  loadBalancer: {}
